services:
  db:
    image: mysql:8.4
    container_name: parksmart_db
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: parksmart
    ports:
      - "3307:3306"
    volumes:
      - parksmart_mysql_data:/var/lib/mysql
      - ./database/parksmart_db.sql:/docker-entrypoint-initdb.d/01_parksmart_db.sql:ro
      - ./database/migrations/02_proveedores.sql:/docker-entrypoint-initdb.d/02_proveedores.sql:ro
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-p$${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    build: .
    container_name: parksmart_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD:-root}@db:3306/parksmart
      SECRET_KEY: ${SECRET_KEY:-cambie-esta-clave-en-produccion}
      ACCESS_TOKEN_MINUTES: ${ACCESS_TOKEN_MINUTES:-480}
      RESET_TOKEN_MINUTES: ${RESET_TOKEN_MINUTES:-15}
      AUTH_DEBUG_RESET_TOKEN: ${AUTH_DEBUG_RESET_TOKEN:-true}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@parksmart.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin123*}
      ADMIN_RESET_PASSWORD_ON_STARTUP: ${ADMIN_RESET_PASSWORD_ON_STARTUP:-true}
      FRONTEND_URL: ${FRONTEND_URL:-http://127.0.0.1:5500}
      NOTIFICATION_MODE: ${NOTIFICATION_MODE:-SIMULATION}
      DEFAULT_PHONE_COUNTRY_CODE: ${DEFAULT_PHONE_COUNTRY_CODE:-+506}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-}
      SMTP_USE_TLS: ${SMTP_USE_TLS:-true}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-}
      TWILIO_SMS_FROM: ${TWILIO_SMS_FROM:-}
      TWILIO_WHATSAPP_FROM: ${TWILIO_WHATSAPP_FROM:-}
    ports:
      - "8000:8000"
volumes:
  parksmart_mysql_data:
