const AUTH_TOKEN_KEY='parksmart_access_token',AUTH_USER_KEY='parksmart_auth_user',AUTH_DEMO_KEY='parksmart_demo_session';
window.parkSmartSession={usuario:null,demo:false};
function obtenerTokenAcceso(){return localStorage.getItem(AUTH_TOKEN_KEY)||''}function obtenerUsuarioGuardado(){try{return JSON.parse(localStorage.getItem(AUTH_USER_KEY)||'null')}catch{return null}}
async function inicializarAutenticacion(){configurarEventosAutenticacion();localStorage.removeItem(AUTH_DEMO_KEY);const tokenReset=new URLSearchParams(location.search).get('reset_token');if(tokenReset){mostrarPantallaAuth('reset');document.getElementById('resetToken').value=tokenReset;return false}const token=obtenerTokenAcceso();if(!token){mostrarPantallaAuth('login');return false}try{const u=await apiGet('/auth/me');guardarSesionAutenticada(token,u);activarSesionVisual(u,false);return true}catch(e){limpiarSesionAutenticada();mostrarPantallaAuth('login');mostrarMensajeAuth('La sesión expiró. Iniciá sesión nuevamente.','error');return false}}
function configurarEventosAutenticacion(){if(window.authEventsConfigured)return;window.authEventsConfigured=true;document.getElementById('loginForm')?.addEventListener('submit',iniciarSesion);document.getElementById('recoveryForm')?.addEventListener('submit',solicitarRestablecimiento);document.getElementById('resetForm')?.addEventListener('submit',restablecerContrasena);document.getElementById('changePasswordForm')?.addEventListener('submit',cambiarContrasena);document.getElementById('adminUserForm')?.addEventListener('submit',crearUsuarioDesdeAdmin);document.getElementById('adminNotificationForm')?.addEventListener('submit',enviarNotificacionDesdeAdmin)}
function mostrarPantallaAuth(v='login'){document.getElementById('authScreen')?.classList.remove('hidden');document.getElementById('appShell')?.classList.add('hidden');document.querySelectorAll('[data-auth-view]').forEach(p=>p.classList.toggle('hidden',p.dataset.authView!==v));const m=document.getElementById('authMessage');if(m)m.className='auth-message hidden'}
function mostrarVistaAuth(v){mostrarPantallaAuth(v)}
function activarSesionVisual(u,demo=false){window.parkSmartSession.usuario=u;window.parkSmartSession.demo=false;document.getElementById('authScreen')?.classList.add('hidden');document.getElementById('appShell')?.classList.remove('hidden');document.body.classList.toggle('admin-session',u.rol==='ADMINISTRADOR');const chip=document.getElementById('profileRole');if(chip)chip.textContent=u.rol==='ADMINISTRADOR'?'Administrador':u.rol==='PROVEEDOR'?'Proveedor':'Cliente';document.getElementById('adminToolsButton')?.classList.toggle('hidden',u.rol!=='ADMINISTRADOR')}
async function iniciarSesion(e){e.preventDefault();const b=document.getElementById('loginButton');b.disabled=true;b.textContent='Verificando...';try{const r=await apiPost('/auth/login',{usuario:document.getElementById('loginUser').value.trim(),contrasena:document.getElementById('loginPassword').value});guardarSesionAutenticada(r.accessToken,r.usuario);location.reload()}catch(x){mostrarMensajeAuth(limpiarMensajeError(x.message),'error')}finally{b.disabled=false;b.textContent='Iniciar sesión'}}
function guardarSesionAutenticada(t,u){localStorage.setItem(AUTH_TOKEN_KEY,t);localStorage.setItem(AUTH_USER_KEY,JSON.stringify(u));if(u.idCliente)localStorage.setItem('parksmart_cliente_id',String(u.idCliente));window.parkSmartSession.usuario=u}
function limpiarSesionAutenticada(){localStorage.removeItem(AUTH_TOKEN_KEY);localStorage.removeItem(AUTH_USER_KEY);localStorage.removeItem(AUTH_DEMO_KEY)}
async function cerrarSesion(){try{if(obtenerTokenAcceso())await apiPost('/auth/logout',{})}catch{}limpiarSesionAutenticada();sessionStorage.clear();location.reload()}function cambiarCuenta(){cerrarSesion()}
function mostrarMensajeAuth(m,t='success'){const e=document.getElementById('authMessage');if(e){e.textContent=m;e.className=`auth-message ${t}`}}
async function solicitarRestablecimiento(e){e.preventDefault();try{const r=await apiPost('/auth/solicitar-restablecimiento',{usuarioOCorreo:document.getElementById('recoveryIdentity').value.trim(),canal:document.getElementById('recoveryChannel').value});mostrarMensajeAuth(r.mensaje,'success');if(r.tokenRestablecimiento){document.getElementById('resetToken').value=r.tokenRestablecimiento;mostrarVistaAuth('reset')}}catch(x){mostrarMensajeAuth(limpiarMensajeError(x.message),'error')}}
async function restablecerContrasena(e){e.preventDefault();if(resetPassword.value!==resetPasswordConfirm.value){mostrarMensajeAuth('Las contraseñas no coinciden.','error');return}try{const r=await apiPost('/auth/restablecer-contrasena',{token:resetToken.value.trim(),nuevaContrasena:resetPassword.value});history.replaceState({},'',location.pathname);mostrarVistaAuth('login');mostrarMensajeAuth(r.mensaje,'success')}catch(x){mostrarMensajeAuth(limpiarMensajeError(x.message),'error')}}
function abrirCambioContrasena(){document.getElementById('changePasswordForm')?.reset();abrirDialogo('changePasswordDialog')}
async function cambiarContrasena(e){e.preventDefault();if(newPassword.value!==confirmNewPassword.value){mostrarToast('Las contraseñas nuevas no coinciden.');return}try{const r=await apiPut('/auth/cambiar-contrasena',{contrasenaActual:currentPassword.value,nuevaContrasena:newPassword.value});cerrarDialogo('changePasswordDialog');mostrarToast(r.mensaje)}catch(x){mostrarToast(limpiarMensajeError(x.message))}}
async function abrirAdministracion(){if(window.parkSmartSession.usuario?.rol!=='ADMINISTRADOR')return;abrirDialogo('adminDialog');await cargarUsuariosAdmin()}
async function cargarUsuariosAdmin(){const c=document.getElementById('adminUsersList');if(!c)return;c.innerHTML='Cargando usuarios...';try{const u=await apiGet('/usuarios/');c.innerHTML=u.map(x=>`<article class="admin-user-row"><strong>${escaparHtml(x.nombreUsuario)}</strong><small>${escaparHtml(x.correoElectronico)}</small><span>${formatearEstado(x.rol)}</span></article>`).join('')}catch(x){c.textContent=limpiarMensajeError(x.message)}}
async function crearUsuarioDesdeAdmin(e){e.preventDefault();try{const role=document.getElementById('adminUserRole').value,id=document.getElementById('adminUserClientId').value.trim();await apiPost('/usuarios/',{nombreUsuario:adminUsername.value.trim(),correoElectronico:adminUserEmail.value.trim(),contrasena:adminUserPassword.value,rol:role,idCliente:id?Number(id):null});e.target.reset();mostrarToast('Usuario creado correctamente');await cargarUsuariosAdmin()}catch(x){mostrarToast(limpiarMensajeError(x.message))}}
async function enviarNotificacionDesdeAdmin(e){e.preventDefault();try{await apiPost('/notificaciones/',{idCliente:Number(adminNotificationClientId.value),tipoNotificacion:'SISTEMA',canal:adminNotificationChannel.value,titulo:adminNotificationTitle.value.trim(),mensaje:adminNotificationMessage.value.trim(),destinatario:adminNotificationRecipient.value.trim()||null,enviarAhora:true});e.target.reset();mostrarToast('Notificación enviada')}catch(x){mostrarToast(limpiarMensajeError(x.message))}}
