let providerMap=null,providerMarker=null;
function inicializarPanelProveedor(){
 if(document.getElementById('providerPanel'))return;
 const panel=document.createElement('section');panel.id='providerPanel';panel.style.cssText='position:fixed;inset:5vh 4vw;z-index:3000;background:#fff;border-radius:20px;padding:22px;overflow:auto;box-shadow:0 20px 60px #0005';
 panel.innerHTML=`<button onclick="document.getElementById('providerPanel').remove()" style="float:right">Cerrar</button><h2>Panel del proveedor</h2><p>Publicá tus sectores y espacios usando coordenadas reales.</p><div id="providerMap" style="height:55vh;border-radius:16px"></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button onclick="providerModoSector()">+ Sector</button><button onclick="providerModoEspacio()">+ Espacio</button><button onclick="cargarReservasProveedor()">Mis reservas</button></div><div id="providerForm"></div><div id="providerReservations"></div>`;document.body.appendChild(panel);providerMap=L.map('providerMap').setView([9.9281,-84.0907],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(providerMap);providerMap.on('click',e=>{if(providerMap._parksmartMode){providerMap._parksmartPoint=e.latlng;providerMarker?.remove();providerMarker=L.marker(e.latlng).addTo(providerMap);renderProviderForm(providerMap._parksmartMode,e.latlng)}});cargarSectoresProveedor()}
function providerModoSector(){providerMap._parksmartMode='sector';document.getElementById('providerForm').innerHTML='<p><b>Sector:</b> tocá el mapa donde estará el sector.</p>'}
function providerModoEspacio(){providerMap._parksmartMode='espacio';document.getElementById('providerForm').innerHTML='<p><b>Espacio:</b> tocá el mapa donde estará el espacio.</p>';}
async function cargarSectoresProveedor(){const data=await apiGet('/proveedores/sectores/mis-sectores');data.forEach(s=>L.marker([s.latitud,s.longitud]).addTo(providerMap).bindPopup(`<b>${s.nombreSector}</b><br>₡${s.precioHora}/hora`));window._providerSectors=data}
function renderProviderForm(mode,p){const sectors=window._providerSectors||[];document.getElementById('providerForm').innerHTML=mode==='sector'?`<form onsubmit="guardarSectorProveedor(event)"><input id="psName" placeholder="Nombre del sector" required><input id="psPrice" type="number" min="0" placeholder="Precio por hora" required><input id="psDesc" placeholder="Descripción"><button>Guardar sector</button></form>`:`<form onsubmit="guardarEspacioProveedor(event)"><select id="peSector" required>${sectors.map(s=>`<option value="${s.idSector}">${s.nombreSector}</option>`).join('')}</select><input id="peCode" placeholder="Código A-01" required><select id="peType"><option>REGULAR</option><option>MOTOCICLETA</option><option>DISCAPACIDAD</option><option>ELECTRICO</option><option>VIP</option></select><button>Guardar espacio</button></form>`;document.getElementById('providerForm').dataset.lat=p.lat;document.getElementById('providerForm').dataset.lng=p.lng}
async function guardarSectorProveedor(e){e.preventDefault();const f=document.getElementById('providerForm');try{await apiPost('/proveedores/sectores',{nombreSector:psName.value,descripcion:psDesc.value||null,latitud:+f.dataset.lat,longitud:+f.dataset.lng,precioHora:+psPrice.value});mostrarToast('Sector publicado correctamente.');location.reload()}catch(x){mostrarToast(limpiarMensajeError(x.message))}}
async function guardarEspacioProveedor(e){e.preventDefault();const f=document.getElementById('providerForm');try{await apiPost('/proveedores/espacios',{idSector:+peSector.value,codigoEspacio:peCode.value,tipoEspacio:peType.value,latitud:+f.dataset.lat,longitud:+f.dataset.lng});mostrarToast('Espacio publicado correctamente.');location.reload()}catch(x){mostrarToast(limpiarMensajeError(x.message))}}
async function cargarReservasProveedor(){const r=await apiGet('/proveedores/reservas');document.getElementById('providerReservations').innerHTML='<h3>Reservas de mis espacios</h3>'+r.map(x=>`<article style="padding:10px;border-bottom:1px solid #ddd"><b>${x.codigoReserva}</b> · ${x.nombreSector} · ${x.codigoEspacio}<br>Cliente: ${x.nombre} ${x.primerApellido}<br>${new Date(x.fechaInicioReserva).toLocaleString()} → ${new Date(x.fechaFinReserva).toLocaleString()} · ${x.estado}</article>`).join('')||'<p>No hay reservas.</p>'}
setTimeout(()=>{if(window.parkSmartSession?.usuario?.rol==='PROVEEDOR'){inicializarPanelProveedor();const b=document.createElement('button');b.textContent='Panel proveedor';b.onclick=inicializarPanelProveedor;b.style.cssText='position:fixed;right:20px;bottom:20px;z-index:2500';document.body.appendChild(b)}},700);
